version: '3.8'

services:
  comercio:
    build: .
    ports:
      - "8082:8082"
    environment:
      DB_URL: jdbc:mysql://comercioDB:3306/comercio_muebles?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
       comercioDB:
         condition: service_healthy
  comercioDB:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: comercio_muebles
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h" , "localhost"]
      timeout: 10s
      retries: 10

volumes:
  db_data: